### ISSUE TITLE
Could you produce a .vsix file out of your project.

### ISSUE THREAD

**Issue by pelsql** [koalamer/vsc-labeled-bookmarks#11]
Having a .vsix file would allow to use it in Azure Data Studio that has a common code base with VsCode.

People going from SSMS to Azure Data Studio miss very much bookmarks in SSMS.

**Comment by koalamer** [comment]
Hello, sorry my notifications were off for a while.

There is a "Download Extension" link on the marketplace page (https://marketplace.visualstudio.com/items?itemName=koalamer.labeled-bookmarks), you can use that.

Cheers
