### ISSUE TITLE
After upgrading to VSCode #1.69, the icon shapes disappeared.

### ISSUE THREAD

**Issue by chfly2000** [koalamer/vsc-labeled-bookmarks#8]
![image](https://user-images.githubusercontent.com/2978451/178130006-9253921a-0955-4288-8142-8dabe706b092.png)

**Comment by koalamer** [comment]
Indeed.

Tried to update vsce and recompile but now I'm getting
`Property 'window' does not exist on type 'typeof import("vscode")'.`
and
`Module '"vscode"' has no exported member 'FileDeleteEvent'.`
kind of errors all over the place.

I'm not a JS/TS programmer and did not manage to find out what's going on so far... Something changed outside the extension.

**Comment by chfly2000** [comment]
Yes, the logic of Icon Uri seems to have changed. If set with _ThemeIcon_, the icon can be displayed.
```js
result.iconPath = vscode_1.ThemeIcon.File; // bookmark.group.decorationSvg;
...
result.iconPath = vscode_1.ThemeIcon.Folder; // group.decorationSvg;
```

![image](https://user-images.githubusercontent.com/2978451/178228393-0af6af75-ad64-4f35-a065-5f6c1d80722e.png)

**Comment by koalamer** [comment]
The compile errors went away all by themselves. Apparently my system just got a little confused because of the updates.

Currently trying to move the gutter icon temp dir elsewhere. So far it seems to work but I'll test it on my work notebook as well.

**Comment by chfly2000** [comment]
Thanks a lot for fixing it!
